# Creates a postgres and adminer container for simple database usage/management during development

services:
  postgres-db:
    image: postgres:18
    networks:
      - database-management
    ports:
      - 5432:5432
    volumes:
      - ../postgres-volume:/var/lib/postgresql/
    environment:
      POSTGRES_DB: budget-api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    networks:
      - database-management
    ports:
      - 8080:8080

networks:
  database-management: 
    driver: bridge