"""Add unique constraint to income

Revision ID: 082f21d5c431
Revises: ceb1ece10372
Create Date: 2026-05-31 10:55:53.857467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '082f21d5c431'
down_revision: Union[str, Sequence[str], None] = 'ceb1ece10372'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('income', 'income_tax',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)
    op.create_unique_constraint("Unique-User-ID", 'income', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("Unique-User-ID", 'income', type_='unique')
    op.alter_column('income', 'income_tax',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)
    # ### end Alembic commands ###
