"""Add contribution and expenses tables

Revision ID: ceb1ece10372
Revises: c7ab904f4a2d
Create Date: 2026-05-16 11:47:37.780827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceb1ece10372'
down_revision: Union[str, Sequence[str], None] = 'c7ab904f4a2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contribution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.NUMERIC(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=511), nullable=False),
    sa.Column('amount', sa.NUMERIC(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('RETIREMENT', 'INVESTMENT', 'SAVINGS', 'PERSONAL_GOAL', 'OTHER', name='contributiontype'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.NUMERIC(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=511), nullable=False),
    sa.Column('cost', sa.NUMERIC(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_debt', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('income', 'income_tax',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('income', 'income_tax',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_table('expense')
    op.drop_table('contribution')
    # ### end Alembic commands ###
